
server.port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:49153/academia
    username: postgres
    password: #mysecretpassword
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace